### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by wangziyu1231** [lonePatient/cw2vec-pytorch#1]
我想问下，zhihu.txt是已经分词过后的数据吗?

**Comment by lonePatient** [comment]
> 我想问下，zhihu.txt是已经分词过后的数据吗?

dataset目录里面包含了数据，已经分好词的。这里只是做下实验。

**Comment by lonePatient** [comment]
@wangziyu1231 dataset目录里面包含了数据，已经分好词的。这里只是做下实验。
